language: python

python:
  - 2.7

before_script:
  - bundle install
  - npm install
  - ./node_modules/.bin/bower install
  - cd test
  - ../node_modules/.bin/bower install
  - cd ..

install: "pip install -r requirements.txt"

script:
  - ./node_modules/.bin/gulp test
  - ./node_modules/.bin/gulp
  - python manage.py collectstatic --noinput
  - python manage.py test
